# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Energyleaf-ML.proto
# flake8: noqa
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x45nergyleaf-ML.proto\x12\renergyleaf_ml\"\\\n\x1f\x44\x65viceClassificationPeakRequest\x12\x39\n\x05peaks\x18\x01 \x03(\x0b\x32*.energyleaf_ml.DeviceClassificationRequest\"\xbd\x01\n\x1b\x44\x65viceClassificationRequest\x12P\n\x0b\x65lectricity\x18\x01 \x03(\x0b\x32;.energyleaf_ml.DeviceClassificationRequest.ElectricityInput\x12\x0f\n\x02id\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x34\n\x10\x45lectricityInput\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05power\x18\x02 \x01(\x01\x42\x05\n\x03_id\"^\n DeviceClassificationPeakResponse\x12:\n\x05peaks\x18\x01 \x03(\x0b\x32+.energyleaf_ml.DeviceClassificationResponse\"\x85\x03\n\x1c\x44\x65viceClassificationResponse\x12R\n\x0b\x65lectricity\x18\x01 \x03(\x0b\x32=.energyleaf_ml.DeviceClassificationResponse.ElectricityOutput\x12\x0f\n\x02id\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\xf8\x01\n\x11\x45lectricityOutput\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05power\x18\x02 \x01(\x01\x12\x1f\n\x17\x64ominant_classification\x18\x03 \x01(\t\x12i\n\x0e\x63lassification\x18\x04 \x03(\x0b\x32Q.energyleaf_ml.DeviceClassificationResponse.ElectricityOutput.ClassificationEntry\x1a\x35\n\x13\x43lassificationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x42\x05\n\x03_idb\x06proto3')



_DEVICECLASSIFICATIONPEAKREQUEST = DESCRIPTOR.message_types_by_name['DeviceClassificationPeakRequest']
_DEVICECLASSIFICATIONREQUEST = DESCRIPTOR.message_types_by_name['DeviceClassificationRequest']
_DEVICECLASSIFICATIONREQUEST_ELECTRICITYINPUT = _DEVICECLASSIFICATIONREQUEST.nested_types_by_name['ElectricityInput']
_DEVICECLASSIFICATIONPEAKRESPONSE = DESCRIPTOR.message_types_by_name['DeviceClassificationPeakResponse']
_DEVICECLASSIFICATIONRESPONSE = DESCRIPTOR.message_types_by_name['DeviceClassificationResponse']
_DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT = _DEVICECLASSIFICATIONRESPONSE.nested_types_by_name['ElectricityOutput']
_DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT_CLASSIFICATIONENTRY = _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT.nested_types_by_name['ClassificationEntry']
DeviceClassificationPeakRequest = _reflection.GeneratedProtocolMessageType('DeviceClassificationPeakRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECLASSIFICATIONPEAKREQUEST,
  '__module__' : 'Energyleaf_ML_pb2'
  # @@protoc_insertion_point(class_scope:energyleaf_ml.DeviceClassificationPeakRequest)
  })
_sym_db.RegisterMessage(DeviceClassificationPeakRequest)

DeviceClassificationRequest = _reflection.GeneratedProtocolMessageType('DeviceClassificationRequest', (_message.Message,), {

  'ElectricityInput' : _reflection.GeneratedProtocolMessageType('ElectricityInput', (_message.Message,), {
    'DESCRIPTOR' : _DEVICECLASSIFICATIONREQUEST_ELECTRICITYINPUT,
    '__module__' : 'Energyleaf_ML_pb2'
    # @@protoc_insertion_point(class_scope:energyleaf_ml.DeviceClassificationRequest.ElectricityInput)
    })
  ,
  'DESCRIPTOR' : _DEVICECLASSIFICATIONREQUEST,
  '__module__' : 'Energyleaf_ML_pb2'
  # @@protoc_insertion_point(class_scope:energyleaf_ml.DeviceClassificationRequest)
  })
_sym_db.RegisterMessage(DeviceClassificationRequest)
_sym_db.RegisterMessage(DeviceClassificationRequest.ElectricityInput)

DeviceClassificationPeakResponse = _reflection.GeneratedProtocolMessageType('DeviceClassificationPeakResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECLASSIFICATIONPEAKRESPONSE,
  '__module__' : 'Energyleaf_ML_pb2'
  # @@protoc_insertion_point(class_scope:energyleaf_ml.DeviceClassificationPeakResponse)
  })
_sym_db.RegisterMessage(DeviceClassificationPeakResponse)

DeviceClassificationResponse = _reflection.GeneratedProtocolMessageType('DeviceClassificationResponse', (_message.Message,), {

  'ElectricityOutput' : _reflection.GeneratedProtocolMessageType('ElectricityOutput', (_message.Message,), {

    'ClassificationEntry' : _reflection.GeneratedProtocolMessageType('ClassificationEntry', (_message.Message,), {
      'DESCRIPTOR' : _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT_CLASSIFICATIONENTRY,
      '__module__' : 'Energyleaf_ML_pb2'
      # @@protoc_insertion_point(class_scope:energyleaf_ml.DeviceClassificationResponse.ElectricityOutput.ClassificationEntry)
      })
    ,
    'DESCRIPTOR' : _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT,
    '__module__' : 'Energyleaf_ML_pb2'
    # @@protoc_insertion_point(class_scope:energyleaf_ml.DeviceClassificationResponse.ElectricityOutput)
    })
  ,
  'DESCRIPTOR' : _DEVICECLASSIFICATIONRESPONSE,
  '__module__' : 'Energyleaf_ML_pb2'
  # @@protoc_insertion_point(class_scope:energyleaf_ml.DeviceClassificationResponse)
  })
_sym_db.RegisterMessage(DeviceClassificationResponse)
_sym_db.RegisterMessage(DeviceClassificationResponse.ElectricityOutput)
_sym_db.RegisterMessage(DeviceClassificationResponse.ElectricityOutput.ClassificationEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT_CLASSIFICATIONENTRY._options = None
  _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT_CLASSIFICATIONENTRY._serialized_options = b'8\001'
  _DEVICECLASSIFICATIONPEAKREQUEST._serialized_start=38
  _DEVICECLASSIFICATIONPEAKREQUEST._serialized_end=130
  _DEVICECLASSIFICATIONREQUEST._serialized_start=133
  _DEVICECLASSIFICATIONREQUEST._serialized_end=322
  _DEVICECLASSIFICATIONREQUEST_ELECTRICITYINPUT._serialized_start=263
  _DEVICECLASSIFICATIONREQUEST_ELECTRICITYINPUT._serialized_end=315
  _DEVICECLASSIFICATIONPEAKRESPONSE._serialized_start=324
  _DEVICECLASSIFICATIONPEAKRESPONSE._serialized_end=418
  _DEVICECLASSIFICATIONRESPONSE._serialized_start=421
  _DEVICECLASSIFICATIONRESPONSE._serialized_end=810
  _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT._serialized_start=555
  _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT._serialized_end=803
  _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT_CLASSIFICATIONENTRY._serialized_start=750
  _DEVICECLASSIFICATIONRESPONSE_ELECTRICITYOUTPUT_CLASSIFICATIONENTRY._serialized_end=803
# @@protoc_insertion_point(module_scope)